name: Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-gm1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: 'pip'
      - run: pip install wget
      - run:  |
          echo "UPDATED=$(python3 game-manual-1.py)" >> $GITHUB_ENV 
      - name: Commit Hash
        continue-on-error: true
        if: env.UPDATED == '1'
        id: commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add gm1.pdf.sha256
          git commit -m "Update gm1.pdf.sha256"
      - name: Update Hash
        if: env.UPDATED == '1' && steps.commit.outcome != 'failure'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Send Notification
        if: env.UPDATED == '1' && steps.commit.outcome != 'failure'
        uses: techulus/push-github-action@1.0.0
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MESSAGE: "GM1 has been Updated"
        
