name: Scrape GM2
on:
  workflow_dispatch:
jobs:
  check-gm2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run:  |
          python3 game-manual-2.py
      - name: Commit Hash
        continue-on-error: true
        if: env.UPDATED == '1'
        id: commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add gm2.pdf.sha256
          git add gm2.pdf
          git commit -m "Update gm2.pdf.sha256"
      - name: Update Hash
        if: env.UPDATED == '1' && steps.commit.outcome != 'failure'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
